"""Independent deterministic market-state calculation core."""

from .clock import MonotonicClock, SystemMonotonicClock, SystemWallClock, VirtualClock, WallClock
from .contracts import (
    DataRequest,
    DataResult,
    DataStatus,
    EngineSignal,
    EngineSnapshot,
    FrozenDataBundle,
    MarketDataEnvelope,
    PayloadKind,
    SignalKind,
    canonical_hash,
    canonical_json,
    deep_freeze,
    evidence_hash,
    semantic_hash,
    trunc_div,
)
from .data import (
    DataContext,
    DataFunction,
    DataProvider,
    CallablePreviousDayStatsProvider,
    FixturePreviousDayStatsProvider,
    PreviousDayStatsFunction,
    ProviderResult,
    TemporalDataGuard,
    freeze_data_results,
    normalize_previous_day_stats_rows,
    provider_result_from_previous_day_rows,
)
from .engine import DeterministicEngine
from .facts import (
    BreadthFacts,
    DataQuality,
    FactResult,
    FactStatus,
    OrderBookFacts,
    PriceFacts,
    SegmentComparison,
    SegmentFrame,
    ThemeFacts,
    VolumeFacts,
    build_segment_frame,
    compare_adjacent_segments,
    compare_segments,
    compute_resting_order_pressure,
)
from .probe import ProbeStrategy
from .q2 import (
    FreshnessPolicy,
    Q2FieldSpec,
    Q2ProjectionSnapshot,
    RedisQ2ProjectionAdapter,
    build_q2_projection,
    classify_equity,
    normalize_q2,
    validate_q2,
)
from .state import CurrentMarketState, MarketStateReducer
from .windows import WindowManager, WindowSnapshot, WindowSpec

__all__ = [
    "BreadthFacts",
    "CurrentMarketState",
    "DataContext",
    "DataFunction",
    "DataProvider",
    "CallablePreviousDayStatsProvider",
    "DataRequest",
    "DataResult",
    "DataStatus",
    "DataQuality",
    "DeterministicEngine",
    "EngineSignal",
    "EngineSnapshot",
    "FrozenDataBundle",
    "FactResult",
    "FactStatus",
    "FixturePreviousDayStatsProvider",
    "MarketDataEnvelope",
    "MarketStateReducer",
    "MonotonicClock",
    "OrderBookFacts",
    "PayloadKind",
    "PriceFacts",
    "PreviousDayStatsFunction",
    "ProviderResult",
    "TemporalDataGuard",
    "normalize_previous_day_stats_rows",
    "provider_result_from_previous_day_rows",
    "ProbeStrategy",
    "Q2ProjectionSnapshot",
    "RedisQ2ProjectionAdapter",
    "FreshnessPolicy",
    "Q2FieldSpec",
    "build_q2_projection",
    "classify_equity",
    "normalize_q2",
    "validate_q2",
    "SignalKind",
    "SegmentComparison",
    "SegmentFrame",
    "SystemMonotonicClock",
    "SystemWallClock",
    "ThemeFacts",
    "VirtualClock",
    "VolumeFacts",
    "WallClock",
    "WindowManager",
    "WindowSnapshot",
    "WindowSpec",
    "build_segment_frame",
    "compare_adjacent_segments",
    "canonical_hash",
    "canonical_json",
    "deep_freeze",
    "evidence_hash",
    "semantic_hash",
    "trunc_div",
    "compare_segments",
    "compute_resting_order_pressure",
    "freeze_data_results",
]
