"""Independent deterministic market-state calculation core."""

from .clock import MonotonicClock, SystemMonotonicClock, SystemWallClock, VirtualClock, WallClock
from .contracts import (
    DataRequest,
    DataResult,
    DataStatus,
    EngineSignal,
    EngineSnapshot,
    FrozenDataBundle,
    MarketDataEnvelope,
    PayloadKind,
    SignalKind,
    canonical_hash,
    canonical_json,
    deep_freeze,
    evidence_hash,
    semantic_hash,
    trunc_div,
)
from .data import (
    DataContext,
    DataFunction,
    DataProvider,
    FixturePreviousDayStatsProvider,
    PreviousDayStatsFunction,
    freeze_data_results,
)
from .engine import DeterministicEngine
from .facts import (
    BreadthFacts,
    DataQuality,
    FactResult,
    FactStatus,
    OrderBookFacts,
    PriceFacts,
    SegmentComparison,
    SegmentFrameFactFunction,
    SegmentFrame,
    ThemeFacts,
    VolumeFacts,
    build_segment_frame,
    compare_segments,
)
from .probe import ProbeStrategy
from .q2 import Q2ProjectionSnapshot, RedisQ2ProjectionAdapter
from .state import CurrentMarketState, MarketStateReducer
from .windows import WindowManager, WindowSnapshot, WindowSpec

__all__ = [
    "BreadthFacts",
    "CurrentMarketState",
    "DataContext",
    "DataFunction",
    "DataProvider",
    "DataRequest",
    "DataResult",
    "DataStatus",
    "DataQuality",
    "DeterministicEngine",
    "EngineSignal",
    "EngineSnapshot",
    "FrozenDataBundle",
    "FactResult",
    "FactStatus",
    "FixturePreviousDayStatsProvider",
    "MarketDataEnvelope",
    "MarketStateReducer",
    "MonotonicClock",
    "OrderBookFacts",
    "PayloadKind",
    "PriceFacts",
    "PreviousDayStatsFunction",
    "ProbeStrategy",
    "Q2ProjectionSnapshot",
    "RedisQ2ProjectionAdapter",
    "SignalKind",
    "SegmentComparison",
    "SegmentFrame",
    "SegmentFrameFactFunction",
    "SystemMonotonicClock",
    "SystemWallClock",
    "ThemeFacts",
    "VirtualClock",
    "VolumeFacts",
    "WallClock",
    "WindowManager",
    "WindowSnapshot",
    "WindowSpec",
    "build_segment_frame",
    "canonical_hash",
    "canonical_json",
    "deep_freeze",
    "evidence_hash",
    "semantic_hash",
    "trunc_div",
    "compare_segments",
    "freeze_data_results",
]
